name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  qr_flutter: ^4.0.0
  unicons: any
  url_launcher: ^6.0.9  # Kept dependency from `master`
  dio: ^4.0.0  # Kept dependency from `master`
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  http: ^0.13.4
  flutter_barcode_scanner: ^2.0.0
  syncfusion_flutter_barcodes: ^19.1.72
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_application_1: ^0.0.2

flutter:
  uses-material-design: true
